apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "kube-ovn-control-plane,kube-ovn-worker"
  type: "centralized"
  external-gw-nic: eth1
  external-gw-addr: "172.19.0.0/16"
