apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    ovn.kubernetes.io/logical_switch: no-bfd-subnet   # replace with your logical switch name
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]

